name: deploy on push
runs-on: ubuntu-latest
steps:
  - name: check out the code to build server
    user: actions/checkout@v3
  - name: copy file to server
    users: appleboy/scp-action@master
    with:
      host: ${{secrets.HOST}}
      username: ${{secret.SSH_USER_NAME}}
      port: ${{secret.SSH_PORT}}
      key: ${{secret.SSH_KEY}}
      source: "./html/*"
      target: "/var/www/html"
      strip_components: 1